name: Build and Publish Docker Images

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: meta_api
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/Njordyy/manhuaseerr-api
          tags: |
            type=raw,value=main,enable=${{ github.ref == 'refs/heads/main' }}
            type=ref,event=tag
            type=sha,format=long

      - uses: docker/build-push-action@v6
        with:
          context: ./api
          push: true
          tags: ${{ steps.meta_api.outputs.tags }}
          labels: ${{ steps.meta_api.outputs.labels }}

      - id: meta_web
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/Njordyy/manhuaseerr-web
          tags: |
            type=raw,value=main,enable=${{ github.ref == 'refs/heads/main' }}
            type=ref,event=tag
            type=sha,format=long

      - uses: docker/build-push-action@v6
        with:
          context: ./web
          push: true
          tags: ${{ steps.meta_web.outputs.tags }}
          labels: ${{ steps.meta_web.outputs.labels }}
